In [14]:
import sys,os,inspect

class testInspect:
    #asdgd
    def __init__(self):
        pass
    def method1(self,a):
        return a
    def method2(self):
        pass

In [15]:
inspect.currentframe()

In [16]:
inspect.getfile(inspect.currentframe())

'<ipython-input-16-a79be5fd2dec>'

In [17]:
sys._getframe().f_code.co_filename

'<ipython-input-17-fcb087034383>'

In [5]:
os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

'C:\\Users\\juni\\pyDeep\\practice'

In [18]:
os.path.dirname(os.path.abspath(sys._getframe().f_code.co_filename))

'C:\\Users\\juni\\pyDeep\\practice'

In [23]:
sys.path

['',
 'C:\\Users\\juni\\Anaconda3\\python36.zip',
 'C:\\Users\\juni\\Anaconda3\\DLLs',
 'C:\\Users\\juni\\Anaconda3\\lib',
 'C:\\Users\\juni\\Anaconda3',
 'C:\\Users\\juni\\AppData\\Roaming\\Python\\Python36\\site-packages',
 'C:\\Users\\juni\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\juni\\Anaconda3\\lib\\site-packages\\Babel-2.5.0-py3.6.egg',
 'C:\\Users\\juni\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\juni\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\juni\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\juni\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\juni\\.ipython']

In [3]:
import tensorflow as tf

In [2]:
weights = tf.Variable(tf.random_normal([784,200],stddev=0.35),name = "weights")

In [7]:
w2 = tf.Variable(weights.initialized_value()*2)
w3 = tf.Variable(weights*2)
print(type(weights.initialized_value()*2))
print(type(weights))
print(type(tf.random_normal([300,100],stddev=0.35)))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.ops.variables.Variable'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [10]:
assert(2 is 2)

In [1]:
from tensorflow.python.client import device_lib

print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 14491886666158811601
]


In [4]:
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

In [5]:
import tensorflow as tf
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)

with tf.Session() as sess:
    print (sess.run(c))

InvalidArgumentError: Cannot assign a device for operation 'MatMul': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/device:GPU:0"](a, b)]]

Caused by op 'MatMul', defined at:
  File "C:\Users\juni\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\juni\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\juni\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\juni\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\juni\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\juni\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\juni\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\Users\juni\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\juni\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\juni\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\juni\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\juni\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\juni\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\juni\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\juni\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\juni\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\juni\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\juni\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\juni\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\juni\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\juni\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-3a5be606bcc9>", line 5, in <module>
    c = tf.matmul(a, b)
  File "C:\Users\juni\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2014, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\Users\juni\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 4567, in mat_mul
    name=name)
  File "C:\Users\juni\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\juni\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Users\juni\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'MatMul': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/device:GPU:0"](a, b)]]


In [6]:
from keras import backend as K
K.tensorflow_backend._get_available_gpus()

Using TensorFlow backend.


[]

In [1]:
import tensorflow as tf
import numpy as np

In [7]:
session = tf.Session()

x = [0., 1., 2., 3., 4., 5., 6., 7.]
y = tf.reshape(x, [4, 2])

unstack_axis1 = tf.unstack(y, axis=1)
print("UNSTACK AXIS 1")
print(session.run(unstack_axis1))

for i, input in enumerate(unstack_axis1):
    print(i, input)
    print(session.run(input))
    print(session.run(tf.nn.dropout(input,0.5)))

UNSTACK AXIS 1
[array([ 0.,  2.,  4.,  6.], dtype=float32), array([ 1.,  3.,  5.,  7.], dtype=float32)]
0 Tensor("unstack_5:0", shape=(4,), dtype=float32)
[ 0.  2.  4.  6.]
[ 0.  4.  0.  0.]
1 Tensor("unstack_5:1", shape=(4,), dtype=float32)
[ 1.  3.  5.  7.]
[  2.   0.  10.  14.]


In [23]:
import re

def _filter(fn):
    filtered_sents = []
    with open(fn, 'r', encoding='utf-8') as f:
        sents = f.readlines()[:100]
        for line in sents:
            print(line)
            word = re.compile('<.*:DT>')
            if word.match(line):
                filtered_sents.append(line.strip())
    return(filtered_sents)

In [24]:
_filter('DT.txt')

<지난주부터:DT>

<지난달 17일:DT>

<2003년 6월:DT>, <지난해 5월:DT>에 이어 <주간:DT>

<6월:DT>

<한 달:DT>


['<지난주부터:DT>',
 '<지난달 17일:DT>',
 '<2003년 6월:DT>, <지난해 5월:DT>에 이어 <주간:DT>',
 '<6월:DT>',
 '<한 달:DT>']

In [5]:
string = '<><><>'
print(string.replace('<','>'))
print(string)

>>>>>>
<><><>


In [4]:
print(4/2)
from __future__ import division
print(int(4/2))

2.0
2


In [20]:
from collections import defaultdict

d1 = dict()
d2 = defaultdict()

In [21]:
print(d1['one'])

KeyError: 'one'

In [22]:
print(d2['two'])

KeyError: 'two'

In [30]:
class test1():
    a=1
    @classmethod
    def __init__(cls):
        cls.a+=1

t1 = test1()

In [31]:
print(t1.a)

2


In [32]:
t2 = test1()
print(t2.a)

3


In [19]:
import re
from konlpy.tag import Kkma

lst = []
with open('RESULT.txt','r',encoding='utf8') as f:
    lines = f.readlines()
    for line in lines:
        line = line.strip()
        word = re.compile('<[^>]*:PU>')
        result= word.findall(line)
        if result:
            lst+=result
slst = set(lst)
for se in slst:
    print(Kkma().pos(se[1:-4]))

[('카지노', 'NNG')]
[('전망', 'NNG'), ('좋', 'VA'), ('은', 'ETD'), ('곳', 'NNG')]
[('경치', 'NNG')]
[('지역', 'NNG'), ('탐방', 'NNG')]
[('별미', 'NNG')]
[('힐링', 'NNG')]
[('활동', 'NNG')]
[('야경', 'NNG')]
[('추억', 'NNG')]
[('마사지', 'NNG')]
[('바다', 'NNG')]
[('문화', 'NNG'), ('탐방', 'NNG')]
[('스노', 'NNG'), ('쿨링', 'NNG')]
[('휴양', 'NNG')]
[('물놀이', 'NNG')]
[('관광지', 'NNG')]
[('문화재', 'NNG')]
[('맛있', 'VA'), ('는', 'ETD')]
[('기념품', 'NNG')]
[('트레킹', 'NNG')]
[('바닷가', 'NNG')]
[('유적지', 'NNG')]
[('불', 'NNG'), ('거리', 'NNG')]
[('보', 'VV'), ('ㄹ', 'ETD'), ('거', 'NNB')]
[('명소', 'NNG')]
[('건축물', 'NNG')]
[('즐기', 'VV'), ('는', 'ETD')]
[('수영', 'NNG')]
[('즐기', 'VV'), ('ㄹ', 'ETD'), ('것', 'NNB')]
[('유흥', 'NNG')]
[('쉬', 'VV'), ('면서', 'ECE')]
[('즐기', 'VV'), ('ㄹ', 'ETD'), ('거리', 'NNG')]
[('놀', 'VV'), ('기', 'ETN'), ('좋', 'VA'), ('은', 'ETD'), ('곳', 'NNG')]
[('문화', 'NNG')]
[('쇼핑', 'NNG')]
[('자식', 'NNG'), ('교육', 'NNG')]
[('이색', 'NNG'), ('경험', 'NNG')]
[('휴식', 'NNG')]
[('야시장', 'NNG')]
[('맛있', 'VA'), ('는', 'ETD'), ('음식', 'NNG')]
[('놀이', 'NNG'), ('

In [29]:
import pandas as pd

df = pd.read_csv('PUclf.csv')
a= list(df['음식'].dropna())

print(list(df['문화']))
print(list(df['휴양']))
print(list(df['활동']))
print(list(df['쇼핑']))

['별미', '맛있는', '야시장', '음식', '먹고', '맛집', '먹으러', '해산물', '식도락', '먹는거', '먹거리', '먹', '맛']
['탐방', '추억', '문화', '관광', '유적지', '볼거', '명소', '건출물', '교육', '이색', '경험', '문명', '체험', '역사', '마을', '사진', '예술', '구경', '볼', nan, nan, nan, nan, nan, nan, nan]
['전망', '경치', '힐링', '야경', '마사지', '휴양', '바닷가', '쉬면', '풍경', '맑은공기', '자연', '경관', '쉼', '온천', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
['카지노', '활동', '물놀이', '바다', '스노쿨링', '트레킹', '즐기는', '수영', '즐길', '유흥', '놀기', '놀이공원', '열기구', '놀거리', '클럽', '해수욕장', '해변', '액티비티', '스카이다이빙', '수상레저', '스포츠', '골프', '서핑', '모험', '즐기는', '놀']
['기념품', '쇼핑', '아이쇼핑', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]


In [6]:
arr = [1,3,2]
arr.sort()
print(arr == [1,2,3])

True


In [5]:
x = y = z = [1,2,3]
print(x is y)

x = y = z =1235123423
print(x is y)

True
True
