In [1]:
# Keras import
import keras
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Activation

# Sklearn import
import sklearn
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [2]:
(x_train,y_train),(x_test,y_test) = cifar10.load_data()
num_classes  = 10
print("x_train shape: {}".format(x_train.shape))#(50000, 32, 32, 3): 32*32의 RGB(3)로 구성된 5만개의 이미지 
print("y_train shape: {}".format(y_train.shape))
print("x_test shape: {}".format(x_test.shape))
print("y_test shape: {}".format(y_test.shape))

x_train shape: (50000, 32, 32, 3)
y_train shape: (50000, 1)
x_test shape: (10000, 32, 32, 3)
y_test shape: (10000, 1)


In [3]:
print(y_train[0])
print()
print(x_train[0])
print()
print(x_train[0][0])
print()
print(x_train[0][0][0])
print()
print(x_train[0][0][0][0])

[6]

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ..., 
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ..., 
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ..., 
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ..., 
 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ..., 
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ..., 
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ..., 
  [216 184 140]
  [151 118  84]
  [123  92  72]]]

[[ 59  62  63]
 [ 43  46  45]
 [ 50  48  43]
 [ 68  54  42]
 [ 98  73  52]
 [119  91  63]
 [139 107  75]
 [145 110  80]
 [149 117  89]
 [149 120  93]
 [131 103  77]
 [125  99  76]
 [142 115  91]
 [144 112  86]
 [137 105  79]
 [129  97  71]
 [137 106  79]
 [134 106  76]
 [124  97  64]
 [139 113  78]
 [139 112  75]
 [133 105  69]
 [136 105  74]
 [139 

In [4]:
x_train = x_train.reshape(50000, 3072)#shape변환
x_test = x_test.reshape(10000, 3072)
x_train = x_train.astype('float32')#형변환
x_test = x_test.astype('float32')
x_train /= 255#정규화
x_test /= 255

print("x_train shape: {}".format(x_train.shape))
print("x_test shape: {}".format(x_test.shape))

x_train shape: (50000, 3072)
x_test shape: (10000, 3072)


In [5]:
y_train = keras.utils.to_categorical(y_train, num_classes)#원핫인코딩으로 전환
y_test = keras.utils.to_categorical(y_test, num_classes)

print("y_train shape: {}".format(y_train.shape))
print("y_test shape: {}".format(y_test.shape))
print(y_train[0])

y_train shape: (50000, 10)
y_test shape: (10000, 10)
[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]


### Dense: 완전 연결 NN레이어
 - 기본parameter: output_dim, input_dim, input_shape, activation
 - 앞 레이어의 출력 개수(output_dim)가 다음 레이어의 입력 개수(input_dim)가 됨
 - 그 외: init(초기화 함수 이름), weights(가중치 초기값), W_regularizer(가중치 정규화), b_regularizer(bias정규화),bias(bias포함 여부)

In [6]:
model = Sequential()#순차적인 layer구조
model.add(Dense(1024, activation='relu', input_shape=(3072,)))#Dense(완전연결 레이어)추가, 첫 번째 레이어만 입력개수 지정
model.add(Dense(1024, activation='relu'))
model.add(Dense(1024, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.summary()
model.compile(
            loss=keras.losses.categorical_crossentropy,
            optimizer='adam',
            metrics=['accuracy']
)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1024)              3146752   
_________________________________________________________________
dense_2 (Dense)              (None, 1024)              1049600   
_________________________________________________________________
dense_3 (Dense)              (None, 1024)              1049600   
_________________________________________________________________
dense_4 (Dense)              (None, 256)               262400    
_________________________________________________________________
dense_5 (Dense)              (None, 10)                2570      
Total params: 5,510,922
Trainable params: 5,510,922
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.fit(
    x_train, 
    y_train,
    epochs=500,
    batch_size=1024,
    verbose=1
)

Epoch 1/500
50000/50000 [==============================] - 15s 302us/step - loss: 2.1778 - acc: 0.2081
Epoch 2/500
50000/50000 [==============================] - 14s 280us/step - loss: 1.8313 - acc: 0.3400
Epoch 3/500
50000/50000 [==============================] - 14s 283us/step - loss: 1.7175 - acc: 0.3805
Epoch 4/500
50000/50000 [==============================] - 14s 279us/step - loss: 1.6511 - acc: 0.4075
Epoch 5/500
50000/50000 [==============================] - 14s 279us/step - loss: 1.5840 - acc: 0.4335
Epoch 6/500
50000/50000 [==============================] - 14s 281us/step - loss: 1.5332 - acc: 0.4544
Epoch 7/500
50000/50000 [==============================] - 14s 284us/step - loss: 1.4925 - acc: 0.4700
Epoch 8/500
50000/50000 [==============================] - 14s 280us/step - loss: 1.4494 - acc: 0.4828
Epoch 9/500
50000/50000 [==============================] - 14s 280us/step - loss: 1.4170 - acc: 0.4956
Epoch 10/500
50000/50000 [==============================] - 14s 282us/ste

50000/50000 [==============================] - 14s 272us/step - loss: 0.0090 - acc: 0.9979
Epoch 80/500
50000/50000 [==============================] - 14s 274us/step - loss: 0.0078 - acc: 0.9986
Epoch 81/500
50000/50000 [==============================] - 14s 272us/step - loss: 0.0063 - acc: 0.9991
Epoch 82/500
50000/50000 [==============================] - 14s 272us/step - loss: 0.0062 - acc: 0.9987
Epoch 83/500
50000/50000 [==============================] - 14s 272us/step - loss: 0.0051 - acc: 0.9991
Epoch 84/500
50000/50000 [==============================] - 14s 271us/step - loss: 0.0064 - acc: 0.9987
Epoch 85/500
50000/50000 [==============================] - 14s 272us/step - loss: 0.0301 - acc: 0.9902
Epoch 86/500
50000/50000 [==============================] - 14s 272us/step - loss: 0.3660 - acc: 0.8863
Epoch 87/500
50000/50000 [==============================] - 14s 273us/step - loss: 0.2121 - acc: 0.9281
Epoch 88/500
50000/50000 [==============================] - 14s 272us/step - 

50000/50000 [==============================] - 14s 273us/step - loss: 4.0943e-05 - acc: 1.0000
Epoch 157/500
50000/50000 [==============================] - 14s 273us/step - loss: 3.9480e-05 - acc: 1.0000
Epoch 158/500
50000/50000 [==============================] - 14s 273us/step - loss: 3.8260e-05 - acc: 1.0000
Epoch 159/500
50000/50000 [==============================] - 14s 277us/step - loss: 3.6979e-05 - acc: 1.0000
Epoch 160/500
50000/50000 [==============================] - 14s 275us/step - loss: 3.5980e-05 - acc: 1.0000
Epoch 161/500
50000/50000 [==============================] - 14s 274us/step - loss: 3.4789e-05 - acc: 1.0000
Epoch 162/500
50000/50000 [==============================] - 14s 273us/step - loss: 3.3769e-05 - acc: 1.0000
Epoch 163/500
50000/50000 [==============================] - 14s 277us/step - loss: 3.2805e-05 - acc: 1.0000
Epoch 164/500
50000/50000 [==============================] - 14s 274us/step - loss: 3.1856e-05 - acc: 1.0000
Epoch 165/500
50000/50000 [======

50000/50000 [==============================] - 14s 274us/step - loss: 6.2259e-06 - acc: 1.0000
Epoch 232/500
50000/50000 [==============================] - 14s 273us/step - loss: 6.0772e-06 - acc: 1.0000
Epoch 233/500
50000/50000 [==============================] - 14s 278us/step - loss: 5.9444e-06 - acc: 1.0000
Epoch 234/500
50000/50000 [==============================] - 14s 274us/step - loss: 5.8122e-06 - acc: 1.0000
Epoch 235/500
50000/50000 [==============================] - 14s 273us/step - loss: 5.6866e-06 - acc: 1.0000
Epoch 236/500
50000/50000 [==============================] - 14s 273us/step - loss: 5.5617e-06 - acc: 1.0000
Epoch 237/500
50000/50000 [==============================] - 14s 273us/step - loss: 5.4250e-06 - acc: 1.0000
Epoch 238/500
50000/50000 [==============================] - 14s 276us/step - loss: 5.3269e-06 - acc: 1.0000
Epoch 239/500
50000/50000 [==============================] - 14s 275us/step - loss: 5.2106e-06 - acc: 1.0000
Epoch 240/500
50000/50000 [======

50000/50000 [==============================] - 14s 274us/step - loss: 1.1373e-06 - acc: 1.0000
Epoch 307/500
50000/50000 [==============================] - 14s 274us/step - loss: 1.1140e-06 - acc: 1.0000
Epoch 308/500
50000/50000 [==============================] - 14s 277us/step - loss: 1.0882e-06 - acc: 1.0000
Epoch 309/500
50000/50000 [==============================] - 14s 275us/step - loss: 1.0655e-06 - acc: 1.0000
Epoch 310/500
50000/50000 [==============================] - 14s 274us/step - loss: 1.0425e-06 - acc: 1.0000
Epoch 311/500
50000/50000 [==============================] - 14s 274us/step - loss: 1.0185e-06 - acc: 1.0000
Epoch 312/500
50000/50000 [==============================] - 14s 273us/step - loss: 9.9735e-07 - acc: 1.0000
Epoch 313/500
50000/50000 [==============================] - 14s 274us/step - loss: 9.7560e-07 - acc: 1.0000
Epoch 314/500
50000/50000 [==============================] - 14s 274us/step - loss: 9.5419e-07 - acc: 1.0000
Epoch 315/500
50000/50000 [======

50000/50000 [==============================] - 14s 274us/step - loss: 2.6456e-07 - acc: 1.0000
Epoch 382/500
50000/50000 [==============================] - 14s 275us/step - loss: 2.6093e-07 - acc: 1.0000
Epoch 383/500
50000/50000 [==============================] - 14s 274us/step - loss: 2.5656e-07 - acc: 1.0000
Epoch 384/500
50000/50000 [==============================] - 14s 274us/step - loss: 2.5256e-07 - acc: 1.0000
Epoch 385/500
50000/50000 [==============================] - 14s 274us/step - loss: 2.5050e-07 - acc: 1.0000
Epoch 386/500
50000/50000 [==============================] - 14s 277us/step - loss: 2.4623e-07 - acc: 1.0000
Epoch 387/500
50000/50000 [==============================] - 14s 274us/step - loss: 2.4220e-07 - acc: 1.0000
Epoch 388/500
50000/50000 [==============================] - 14s 274us/step - loss: 2.3835e-07 - acc: 1.0000
Epoch 389/500
50000/50000 [==============================] - 14s 274us/step - loss: 2.3544e-07 - acc: 1.0000
Epoch 390/500
50000/50000 [======

50000/50000 [==============================] - 14s 278us/step - loss: 1.3147e-07 - acc: 1.0000
Epoch 457/500
50000/50000 [==============================] - 14s 275us/step - loss: 1.3103e-07 - acc: 1.0000
Epoch 458/500
50000/50000 [==============================] - 14s 276us/step - loss: 1.3056e-07 - acc: 1.0000
Epoch 459/500
50000/50000 [==============================] - 14s 274us/step - loss: 1.3004e-07 - acc: 1.0000
Epoch 460/500
50000/50000 [==============================] - 14s 274us/step - loss: 1.2957e-07 - acc: 1.0000
Epoch 461/500
50000/50000 [==============================] - 14s 275us/step - loss: 1.2914e-07 - acc: 1.0000
Epoch 462/500
50000/50000 [==============================] - 14s 275us/step - loss: 1.2873e-07 - acc: 1.0000
Epoch 463/500
50000/50000 [==============================] - 14s 274us/step - loss: 1.2843e-07 - acc: 1.0000
Epoch 464/500
50000/50000 [==============================] - 14s 275us/step - loss: 1.2797e-07 - acc: 1.0000
Epoch 465/500
50000/50000 [======

In [8]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy: {}%'.format(score[1]*100))

Test loss: 5.32779613876
Test accuracy: 53.93%
