In [1]:
# Keras import
import keras
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Activation

# Sklearn import
import sklearn
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [2]:
(x_train,y_train),(x_test,y_test) = cifar10.load_data()
num_classes  = 10
print("x_train shape: {}".format(x_train.shape))#(50000, 32, 32, 3): 32*32의 RGB(3)로 구성된 5만개의 이미지 
print("y_train shape: {}".format(y_train.shape))
print("x_test shape: {}".format(x_test.shape))
print("y_test shape: {}".format(y_test.shape))

x_train shape: (50000, 32, 32, 3)
y_train shape: (50000, 1)
x_test shape: (10000, 32, 32, 3)
y_test shape: (10000, 1)


In [3]:
print(y_train[0])
print()
print(x_train[0])
print()
print(x_train[0][0])
print()
print(x_train[0][0][0])
print()
print(x_train[0][0][0][0])

[6]

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ..., 
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ..., 
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ..., 
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ..., 
 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ..., 
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ..., 
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ..., 
  [216 184 140]
  [151 118  84]
  [123  92  72]]]

[[ 59  62  63]
 [ 43  46  45]
 [ 50  48  43]
 [ 68  54  42]
 [ 98  73  52]
 [119  91  63]
 [139 107  75]
 [145 110  80]
 [149 117  89]
 [149 120  93]
 [131 103  77]
 [125  99  76]
 [142 115  91]
 [144 112  86]
 [137 105  79]
 [129  97  71]
 [137 106  79]
 [134 106  76]
 [124  97  64]
 [139 113  78]
 [139 112  75]
 [133 105  69]
 [136 105  74]
 [139 

In [4]:
x_train = x_train.reshape(50000, 3072)#shape변환
x_test = x_test.reshape(10000, 3072)
x_train = x_train.astype('float32')#형변환
x_test = x_test.astype('float32')
x_train /= 255#정규화
x_test /= 255

print("x_train shape: {}".format(x_train.shape))
print("x_test shape: {}".format(x_test.shape))

x_train shape: (50000, 3072)
x_test shape: (10000, 3072)


In [5]:
y_train = keras.utils.to_categorical(y_train, num_classes)#원핫인코딩으로 전환
y_test = keras.utils.to_categorical(y_test, num_classes)

print("y_train shape: {}".format(y_train.shape))
print("y_test shape: {}".format(y_test.shape))
print(y_train[0])

y_train shape: (50000, 10)
y_test shape: (10000, 10)
[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]


### Dense: 완전 연결 NN레이어
 - 기본parameter: output_dim, input_dim, input_shape, activation
 - 앞 레이어의 출력 개수(output_dim)가 다음 레이어의 입력 개수(input_dim)가 됨
 - 그 외: init(초기화 함수 이름), weights(가중치 초기값), W_regularizer(가중치 정규화), b_regularizer(bias정규화),bias(bias포함 여부)

In [6]:
model = Sequential()#순차적인 layer구조
model.add(Dense(1536, activation='relu', input_shape=(3072,)))#Dense(완전연결 레이어)추가, 첫 번째 레이어만 입력개수 지정
model.add(Dense(1024, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.summary()
model.compile(
            loss=keras.losses.categorical_crossentropy,
            optimizer='adam',
            metrics=['accuracy']
)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1536)              4720128   
_________________________________________________________________
dense_2 (Dense)              (None, 1024)              1573888   
_________________________________________________________________
dense_3 (Dense)              (None, 256)               262400    
_________________________________________________________________
dense_4 (Dense)              (None, 64)                16448     
_________________________________________________________________
dense_5 (Dense)              (None, 10)                650       
Total params: 6,573,514
Trainable params: 6,573,514
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.fit(
    x_train, 
    y_train,
    epochs=30,
    batch_size=3072,
    verbose=1
)

Epoch 1/30
50000/50000 [==============================] - 15s 297us/step - loss: 2.6100 - acc: 0.1183
Epoch 2/30
50000/50000 [==============================] - 13s 252us/step - loss: 2.1115 - acc: 0.2137
Epoch 3/30
50000/50000 [==============================] - 13s 257us/step - loss: 1.9857 - acc: 0.2709
Epoch 4/30
50000/50000 [==============================] - 13s 254us/step - loss: 1.9009 - acc: 0.3143
Epoch 5/30
50000/50000 [==============================] - 13s 257us/step - loss: 1.8519 - acc: 0.3374
Epoch 6/30
50000/50000 [==============================] - 13s 255us/step - loss: 1.8061 - acc: 0.3524
Epoch 7/30
50000/50000 [==============================] - 13s 255us/step - loss: 1.7633 - acc: 0.3691
Epoch 8/30
50000/50000 [==============================] - 13s 255us/step - loss: 1.7249 - acc: 0.3835
Epoch 9/30
50000/50000 [==============================] - 13s 255us/step - loss: 1.6887 - acc: 0.3957
Epoch 10/30
50000/50000 [==============================] - 13s 255us/step - loss: 

In [8]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy: {}%'.format(score[1]*100))

Test loss: 1.38883708305
Test accuracy: 50.080000000000005%
